### ISSUE TITLE
Unable to compile macOS 10.13.2: error: unknown directive

### ISSUE THREAD

**Issue by nh13** [williamslab/ped-sim#1]
```bash
all  -O2 -o main.o -c main.cc
g++ -MMD -std=c++11 -Wall  -O2 -o cmdlineopts.o -c cmdlineopts.cc
g++ -MMD -std=c++11 -Wall  -O2 -o cointerfere.o -c cointerfere.cc
gcc -MMD -Wall  -O2 -o memcpy.o -c memcpy.c
<inline asm>:1:1: error: unknown directive
.symver memcpy, memcpy@GLIBC_2.2.5
^
1 error generated.
make: *** [memcpy.o] Error 1
```

**Comment by williamslab** [comment]
While I aim for the tool to be useful, it is primarily coded with the Linux environment in mind. It seems that you found a solution, and that's something you'll have to implement on your own.

**Comment by williamslab** [comment]
FYI, while memcpy.c remains in the repository, the default binary that the Makefile generates no longer compiles/uses this.
