### ISSUE TITLE
segfault?

### ISSUE THREAD

**Issue by genignored** [williamslab/ped-sim#12]
Hi,

I'm not sure if it's an issue in ped-sim, or in the structure of my input VCF, but when trying to run ped-sim and get out a vcf file, I am getting a segfault as soon as it starts writing out the new vcf.  

if it helps, I ran gdb on the run that is failing, which is attached. 

Any help would be very much appreciated.

Starting program: /data/projects/skate/data/ped-sim/1000G_high/../../../software/ped-sim/ped-sim -d full_half_1st_2nd_cousins.def -m refined_mf.simmap -o test_cousins_High_confidence1000G --intf nu_p_campbell.tsv -i test2.vcf --keep_phase
Pedigree simulator!  v1.1.11    (Released 19 Sep 2020)

  Def file:             full_half_1st_2nd_cousins.def
  Map file:             refined_mf.simmap
  Input VCF:            test2.vcf
  Output prefix:        test_cousins_High_confidence1000G

  Random seed:          641804785

  Interference file:    nu_p_campbell.tsv

  Genotype error rate:  1.0e-03
  Opposite homozygous error rate:       0.00
  Missingness rate:     1.0e-03
  Pseudo-haploid rate:  0

  Not retaining extra samples in output VCF (printing only simulated samples)
  Output VCF will contain phased data

Simulating haplotype transmissions... done.
Printing IBD segments... done.
Reading input VCF meta data... done.
  Input contains 433 samples, using 17 as founders, and retaining 0
Generating VCF file...
Program received signal SIGSEGV, Segmentation fault.
0x000000000041806c in void makeVCF<_IO_FILE*>(std::vector<SimDetails, std::allocator<SimDetails> >&, Person*****, int, char const*, char*, GeneticMap&, _IO_FILE**) ()
Missing separate debuginfos, use: debuginfo-install glibc-2.17-322.el7_9.x86_64 libgcc-4.8.5-44.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64
(gdb)

**Comment by genignored** [comment]
Aha.

So, problem is that vcf was reporting as unphased (0/0) rather than phased.  It would be nice, though to have a warning if that is the case, instead of segfaulting?

**Comment by williamslab** [comment]
Ah, thanks for digging into this. I'll get the code to check as you suggest and print an error/warning instead of segfaulting.

**Comment by williamslab** [comment]
Just pushed a fix for this. I tested it, but if you can do so as well, I can close this issue.

**Comment by genignored** [comment]
Works like a charm!  Thank you!

**Comment by williamslab** [comment]
Awesome!
