### ISSUE TITLE
seg fault 

### ISSUE THREAD

**Issue by sanjaynagi** [williamslab/ped-sim#19]
Hi there :)

I'm getting a seg fault when working with the following command + genetic map. No VCF, just simulating a pedigree. Just working with the example def file for now. The command i used:

```
/workflow/scripts/ped-sim/ped-sim -d workflow/scripts/ped-sim/example/cousins-1st_half_to_3rd.def -m results/ped-sim-ag.gmap -o ped-sim --pois
```
and the genetic map:

2RL	1	0.0
2RL	58984778	117.97
2RL	61545105	119.25
2RL	61645106	119.25
2RL	64076722	120.466
2RL	64132875	120.578
2RL	66687494	121.855
2RL	66724067	121.929
2RL	67433980	122.284
2RL	111009430	209.434
3RL	1	0.0
3RL	38988757	77.978
3RL	41860198	79.413
3RL	52161877	100.017
3RL	53200684	100.536
3RL	53200685	100.536
3RL	55015803	101.444
3RL	55097514	101.607
3RL	57435893	102.776
3RL	57465397	102.83500000000001
3RL	58232376	103.219
3RL	95164119	177.082

Here is the log:

[ped-sim.log](https://github.com/williamslab/ped-sim/files/13950577/ped-sim.log)

Thank you.

**Comment by sanjaynagi** [comment]
have tried compiling with both GSL and boost, same error

**Comment by sanjaynagi** [comment]
OK, it works if i just supply only one chromosome in the genetic map

**Comment by sanjaynagi** [comment]
Which i guess is fine, I can just supply one chromosome at a time (I only have 3). closing this issue. 

Thanks for the software, looks great!

**Comment by williamslab** [comment]
Hi!

Hmm, I tried running version 1.4 of Ped-sim using that command line and your genetic map and am not seeing a segfault. I also used Valgrind to see if there were any memory errors and nothing showed up. Do you have a setup to run [valgrind](https://valgrind.org/) on this? Happy to fix any bugs that we can find the source of.

Best,
Amy
