### ISSUE TITLE
Assigning VCF files to founders directly rather than randomly

### ISSUE THREAD

**Issue by freshspaceoctopus** [williamslab/ped-sim#20]
Hello,

I would like to assign VCF file founders directly to a pedigree rather than randomly assigning them to founders.
Is there an internal way to do so? Or do I need to do this manually?

**Comment by williamslab** [comment]
Funny you should be interested in this now. A student has been working on something along these lines and we could hopefully extend his work to be more user-friendly. (At the moment, it requires knowledge of how Ped-sim internally tracks simulated founders.) Let me find some time to work on this. I'm hopeful we could get this done within the next month. Wish I had more time to devote to this right away. I'll follow up.

**Comment by freshspaceoctopus** [comment]
> Funny you should be interested in this now. A student has been working on something along these lines and we could hopefully extend his work to be more user-friendly. (At the moment, it requires knowledge of how Ped-sim internally tracks simulated founders.) Let me find some time to work on this. I'm hopeful we could get this done within the next month. Wish I had more time to devote to this right away. I'll follow up.

That's great news! I wasn't familiar with C or anything programming related, so the only way was to create every parent pair manually...

Thank you for the wonderful simulator, and do let us know when you update the feature.

**Comment by williamslab** [comment]
Reopening this. Hoping to have a version that does this this month!

**Comment by williamslab** [comment]
Got this working! Would have finished a couple weeks ago but several things came up. I did test it but if you encounter bugs, please post here!

**Comment by williamslab** [comment]
Also Thanks to @williamscole for his help with this!

**Comment by freshspaceoctopus** [comment]
Thank you @williamslab  and @williamscole ! I will definetly let you know if we encounter any bugs, if there are any.
