### ISSUE TITLE
Unable to create specify a simple three-generation pedigree

### ISSUE THREAD

**Issue by nh13** [williamslab/ped-sim#6]
I'd like to specify which reproducing parent from a branch in  previous generation to use, but we only get the first one.
> If two parents are listed as in [parent_branch1]_[parent_branch2], the two reproducing parents in the indicated branches (from the previous generation) have children.

For example, I want:
![img_7130](https://user-images.githubusercontent.com/846274/51078072-fa1d1600-166c-11e9-9b63-45ccbd5b112a.JPG)

But the closest def I could create was:
```
def example 1 3
1 1 3
2 2 3 1:1 2:2 3:3
3 2 2 1:1_2 2:2_3
```
which gives:
![pedigree](https://user-images.githubusercontent.com/846274/51078084-26389700-166d-11e9-983c-688073b5bbd4.png)

**Comment by williamslab** [comment]
Only one person per branch is allowed to reproduce. This is the reason that it's feasible to create multiple branches: if you have six branches in generation 2, you can get the mating structure you want.

**Comment by nh13** [comment]
Here's the def file for any future individual:
```
def example 1 3
1 1 3
2 1 6
3 2 2 1:2_3 2:4_5
```
