### ISSUE TITLE
Output VCF.gz is not block compressed

### ISSUE THREAD

**Issue by nh13** [williamslab/ped-sim#7]
When the input VCF is compressed (.gz using bgzip), the output should also be block-compressed.  Unfortunately, it is gzip compressed.  This is not compatible with downstream tools.  See how samtools/htslib outputs vcfs.

**Comment by williamslab** [comment]
Yes, this is an issue. I don't have the bandwidth to look up how to use the bgzip libraries currently. I'm open to you submitting a pull request if you code support for bgzip format output.
