### ISSUE TITLE
Zero-crossover percentages

### ISSUE THREAD

**Issue by mjpeach** [williamslab/ped-sim#8]
I've been working on an implementation of the Broman & Weber (Interference-only) model (in Microsoft Excel) and have used the FHS & AGRE data to calibrate the 'nu' values; I've had the luxury of being able to calculate (1 - G*) to set the zero-crossover rates, but on comparison with the data reported in Fledel-Alon et al I've found it necessary to scale the rates by 1/sqrt(2) to balance the model in agreement with both data-sets. I haven't been able to find any other data-sources for the zero crossover rates; it's also possible that I've made a mistake somewhere, but I thought it was worth a mention.

Regards,
Malcolm Peach

**Comment by williamslab** [comment]
This is interesting. I'd be curious to know whether the zero crossover rates are different when using Ped-sim. From your other post, it sounds like you're using a different model. I'm going to close this issue, but follow up with me, preferably by email, or reopen the issue here if that's better.
