### ISSUE TITLE
Coin-toss on First Cross-over

### ISSUE THREAD

**Issue by mjpeach** [williamslab/ped-sim#9]
The First Crossover (generated from the G* array) has a coin-toss associated with it although the zero-crossovers decision has already been made... I think that means there is also a zero-crossovers path through the crossovers section (i.e. through the coin-tosses)?

**Comment by williamslab** [comment]
The Housworth and Stahl model describes distances between events in the tetrad. This includes the first event  (Appendix A of their 2003 AJHG paper). Incidentally, this code is only a slight modification to Karl Broman's simStahl() R function in the xoi package.
